### ISSUE TITLE
Trouble connecting wallet on Android

### ISSUE THREAD

**Issue by Rhodzy555** [Polar-DANO/dapp-polarnodes.finance#6]
I keep trying to buy a Node and my Metamask wallet won't connect. I've tried on my Chrome browser and on the Metamask browser. Using both Metamask and Wallet Connect from the Polar Nodes website. It either doesn't do anything when I try to connect or tells me to install Metamask. I am on the Avalanche network in my wallet. Any help would be great, I'd like to start earning.

**Comment by Polar-DANO** [comment]
fixed
